DELETE https://phonebook-service-w3i7.onrender.com/api/persons/1

###
GET https://phonebook-service-w3i7.onrender.com/api/persons


###
POST https://phonebook-service-w3i7.onrender.com/api/persons
Content-Type: application/json

{
    "name": "John Paul",
    "number": 123
}